TAG: 'baseline'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 3
PRECISION: 16

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

PROBABILISTIC:
  ENABLED: True

MODEL:
  BN_MOMENTUM: 0.05
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True

INSTANCE_FLOW:
  ENABLED: True

OPTIMIZER:
  LR: 3e-4

N_WORKERS: 20
