_BASE_: '../baseline.yml'

TAG: 'lyft_baseline'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 3
TIME_RECEPTIVE_FIELD: 5
N_FUTURE_FRAMES: 10

DATASET:
  NAME: 'lyft'

IMAGE:
  H: 1080
  W: 1920
  RESIZE_SCALE: 0.25

MODEL:
  SUBSAMPLE: True
